export const orderList = [
  {
    invoice: '1001',
    userName: "Manik Mia",
    books: [
      { 
        id:'74111', 
        title: "Lilabotir Mrittu", 
        author: "Humayun Ahmed", 
        price: "100",
        image: "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/7fcc71de9_195615.jpg",
        publisher: "Prothoma Prokashoni",
        cover: "Papercover",
        condition: "Good",
        print: "Publisher Print"
      },
      { 
        id:'74111', 
        title: "Lilabotir Mrittu", 
        author: "Humayun Ahmed", 
        price: "100",
        image: "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/7fcc71de9_195615.jpg",
        publisher: "Prothoma Prokashoni",
        cover: "Papercover",
        condition: "Good",
        print: "Publisher Print"
      },
      { 
        id:'74111', 
        title: "Lilabotir Mrittu", 
        author: "Humayun Ahmed", 
        price: "100",
        image: "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/7fcc71de9_195615.jpg",
        publisher: "Prothoma Prokashoni",
        cover: "Papercover",
        condition: "Good",
        print: "Publisher Print"
      },
      { 
        id:'74111', 
        title: "Lilabotir Mrittu", 
        author: "Humayun Ahmed", 
        price: "100",
        image: "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/7fcc71de9_195615.jpg",
        publisher: "Prothoma Prokashoni",
        cover: "Papercover",
        condition: "Good",
        print: "Publisher Print"
      },{ 
        id:'74111', 
        title: "Lilabotir Mrittu", 
        author: "Humayun Ahmed", 
        price: "100",
        image: "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/7fcc71de9_195615.jpg",
        publisher: "Prothoma Prokashoni",
        cover: "Papercover",
        condition: "Good",
        print: "Publisher Print"
      },
    ],
    shippingName: "Manik Chad",
    phoneNumber: ["01522255521", "01753544225"],
    address: "Av-5, Mirpur-11, Dhaka-1216",
    total: '547',
    paid: '100',
    orderStatus: "New",
  },
  {
    invoice: '1002',
    userName: "Shakil",
    books: [
      { 
        id:'74111', 
        title: "Lilabotir Mrittu", 
        author: "Humayun Ahmed", 
        price: "100",
        image: "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/7fcc71de9_195615.jpg",
        publisher: "Prothoma Prokashoni",
        cover: "Papercover",
        condition: "Good",
        print: "Publisher Print"
      },
      { 
        id:'74111', 
        title: "Lilabotir Mrittu", 
        author: "Humayun Ahmed", 
        price: "100",
        image: "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/7fcc71de9_195615.jpg",
        publisher: "Prothoma Prokashoni",
        cover: "Papercover",
        condition: "Good",
        print: "Publisher Print"
      },
      { 
        id:'74111', 
        title: "Lilabotir Mrittu", 
        author: "Humayun Ahmed", 
        price: "100",
        image: "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/7fcc71de9_195615.jpg",
        publisher: "Prothoma Prokashoni",
        cover: "Papercover",
        condition: "Good",
        print: "Publisher Print"
      },
    ],
    shippingName: "Mehedi Hasan Shakil",
    phoneNumber: ["01745885548", "01753544227"],
    address: "Av-5, Mirpur-11, Dhaka-1216",
    total: '1042',
    paid: '100',
    orderStatus: "New",
  },
  {
    invoice: '1003',
    userName: "Sayem",
    books: [
      { 
        id:'74111', 
        title: "Lilabotir Mrittu", 
        author: "Humayun Ahmed", 
        price: "100",
        image: "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/7fcc71de9_195615.jpg",
        publisher: "Prothoma Prokashoni",
        cover: "Papercover",
        condition: "Good",
        print: "Publisher Print"
      },
      { 
        id:'74111', 
        title: "Lilabotir Mrittu", 
        author: "Humayun Ahmed", 
        price: "100",
        image: "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/7fcc71de9_195615.jpg",
        publisher: "Prothoma Prokashoni",
        cover: "Papercover",
        condition: "Good",
        print: "Publisher Print"
      },
      { 
        id:'74111', 
        title: "Lilabotir Mrittu", 
        author: "Humayun Ahmed", 
        price: "100",
        image: "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/7fcc71de9_195615.jpg",
        publisher: "Prothoma Prokashoni",
        cover: "Papercover",
        condition: "Good",
        print: "Publisher Print"
      },
    ],
    shippingName: "Md Solim Ullah",
    phoneNumber: ["01789486529"],
    address: "Av-5, Mirpur-11, Dhaka-1216",
    total: '879',
    paid: '100',
    orderStatus: "Packaging Completed",
  },
  {
    invoice: '1004',
    userName: "Tamzid",
    books: [
      { 
        id:'74111', 
        title: "Lilabotir Mrittu", 
        author: "Humayun Ahmed", 
        price: "100",
        image: "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/7fcc71de9_195615.jpg",
        publisher: "Prothoma Prokashoni",
        cover: "Papercover",
        condition: "Good",
        print: "Publisher Print"
      },{ 
        id:'74111', 
        title: "Lilabotir Mrittu", 
        author: "Humayun Ahmed", 
        price: "100",
        image: "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/7fcc71de9_195615.jpg",
        publisher: "Prothoma Prokashoni",
        cover: "Papercover",
        condition: "Good",
        print: "Publisher Print"
      },{ 
        id:'74111', 
        title: "Lilabotir Mrittu", 
        author: "Humayun Ahmed", 
        price: "100",
        image: "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/7fcc71de9_195615.jpg",
        publisher: "Prothoma Prokashoni",
        cover: "Papercover",
        condition: "Good",
        print: "Publisher Print"
      },
    ],
    shippingName: "Tamzid da choto vai",
    phoneNumber: ["01478632854"],
    address: "Av-5, Mirpur-11, Dhaka-1216",
    total: '125',
    paid: '100',
    orderStatus: "Packaging Completed",
  },
  {
    invoice: '1005',
    userName: "Shuvro",
    books: [
      { 
        id:'74111', 
        title: "Lilabotir Mrittu", 
        author: "Humayun Ahmed", 
        price: "100",
        image: "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/7fcc71de9_195615.jpg",
        publisher: "Prothoma Prokashoni",
        cover: "Papercover",
        condition: "Good",
        print: "Publisher Print"
      },{ 
        id:'74111', 
        title: "Lilabotir Mrittu", 
        author: "Humayun Ahmed", 
        price: "100",
        image: "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/7fcc71de9_195615.jpg",
        publisher: "Prothoma Prokashoni",
        cover: "Papercover",
        condition: "Good",
        print: "Publisher Print"
      },{ 
        id:'74111', 
        title: "Lilabotir Mrittu", 
        author: "Humayun Ahmed", 
        price: "100",
        image: "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/7fcc71de9_195615.jpg",
        publisher: "Prothoma Prokashoni",
        cover: "Papercover",
        condition: "Good",
        print: "Publisher Print"
      },
    ],
    shippingName: "ShuvroNil PukeLal",
    phoneNumber: ["01784257111"],
    address: "Av-5, Mirpur-11, Dhaka-1216",
    total: '963',
    paid: '100',
    orderStatus: "New",
  },
];

export const types = [
  "New",
  "Packaging Completed",
  "On Delivery",
  "Delivered",
  "COD Clear",
  "All",
];
