export const book = {
    "url": '/frame.png',
    "title": "book 1",
    "Author": "হুমায়ূন আহমেদ",
    "Publisher": "বিশ্বসাহিত্য কেন্দ্র",
    "Edition": "2nd Editor, 2015",
    "Translator": "মোতাহের হোসেন চৌধুরী",
    "ISBN": 9841803593,
    "Country": "বাংলাদেশ",
    "Cover": ['Hardcover', 'Paperback'],
    "PrintQuality": ['Publisher Print', 'Local Print', 'Premium (Local)'],
    "Condition": ['New', 'Like New', 'Very Good', 'Good', 'Acceptable'],
    "Category": "অনুবাদ: প্রবন্ধ",
    "Rating": "***",
    "Review": "5 people reviewed",
    "Language": "বাংলা",
    "AvailableCopy": 100,
    "Popularity": "high",
    "PrintType": "Original",
    "NoOfPages": "75",
    "priceNew": "100",
    "priceOld": "60",
    "id": 1
  }