# Generated by Django 4.0.5 on 2022-08-25 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=150)),
                ('edition', models.CharField(max_length=25)),
                ('covertype', models.CharField(max_length=25)),
                ('printtype', models.CharField(max_length=25)),
                ('popularity', models.CharField(max_length=25)),
                ('noofpages', models.IntegerField()),
                ('condition', models.CharField(max_length=25)),
                ('publication_year', models.DateTimeField()),
                ('summary', models.CharField(max_length=512)),
                ('bookshelf_row', models.IntegerField()),
                ('bookshelf_column', models.IntegerField()),
                ('sold', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='bookcover')),
            ],
        ),
        migrations.CreateModel(
            name='BookBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=15, null=True)),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('translator', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.CharField(max_length=50)),
                ('category_tags', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=256)),
                ('base_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('base_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.CharField(max_length=512)),
                ('thana', models.CharField(max_length=25)),
                ('district', models.CharField(max_length=25)),
                ('payment_type', models.CharField(max_length=25)),
                ('payment_gateway', models.CharField(max_length=25)),
                ('datetime', models.DateTimeField()),
                ('shipping_status', models.CharField(max_length=25)),
                ('trxid', models.CharField(blank=True, max_length=30, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('comment_customer', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=25)),
                ('base_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sender')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('availability_comment', models.CharField(max_length=256)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.book')),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shippingdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.bookbase'),
        ),
    ]
